/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import clases.Bovino;
import clases.Conexion;
import clases.Felino;
import clases.Suculenta;
import clases.Verdura;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Jose David
 */
public class InformacionCadaEjemplar2 extends javax.swing.JFrame {
    public static SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    static Connection cn;
    /**
     * Creates new form InformacionCadaEjemplar2
     */
    public InformacionCadaEjemplar2() {
        initComponents();
        this.setLocationRelativeTo(null);
        cambiartxt();
        Conexion cx = new Conexion();
        cn = cx.conectarMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDato1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDato2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDato3 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre");

        jLabel2.setText("Fecha de Nacimiento");

        jLabel3.setText("Calorias por porcion");

        txtDato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDato3ActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        jLabel4.setText("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDato1)
                            .addComponent(txtDato2)
                            .addComponent(txtDato3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDato3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDato3ActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
        InformacionCadaEjemplar a = new InformacionCadaEjemplar();
        a.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
    String traerservivo = (String) InformacionCadaEjemplar.jcElegir.getSelectedItem();
    Date dato2 = null;
        if(traerservivo=="Bovinos"){
             String dato1 = txtDato1.getText();
        try {
            dato2 = sdf.parse(txtDato2.getText());
        } catch (ParseException ex) {
            Logger.getLogger(InformacionCadaEjemplar2.class.getName()).log(Level.SEVERE, null, ex);
        }
            int dato3 = Integer.parseInt(txtDato3.getText());
           Bovino nuevobovino = new Bovino(dato1,dato2,dato3); 
           Bovino.guardarBovino(nuevobovino, cn);
        
        }else if(traerservivo=="Felinos"){
            String dato1 = txtDato1.getText();
        try {
            dato2 = sdf.parse(txtDato2.getText());
        } catch (ParseException ex) {
            Logger.getLogger(InformacionCadaEjemplar2.class.getName()).log(Level.SEVERE, null, ex);
        }
            String dato3 = txtDato3.getText();
           Felino nuevofelino = new Felino(dato1,dato2,dato3); 
           Felino.guardarFelino(nuevofelino, cn);
        
        }else if(traerservivo=="Suculentas"){
             String dato1 = txtDato1.getText();
            String dato = txtDato2.getText();
            String dato3 = txtDato3.getText();
           Suculenta nuevoSuculenta = new Suculenta(dato1,dato,dato3); 
           Suculenta.guardarSuculenta(nuevoSuculenta, cn);

        }else if (traerservivo=="Verduras"){
            String dato1 = txtDato1.getText();
            String dato = txtDato2.getText();
            int dato3 = Integer.parseInt(txtDato3.getText());
           Verdura nuevoVerdura = new Verdura(dato1,dato,dato3); 
           Verdura.guardarVerdura(nuevoVerdura, cn);
        }
    }//GEN-LAST:event_btnAceptarMouseClicked
    public void cambiartxt(){
        String traerservivo = (String) InformacionCadaEjemplar.jcElegir.getSelectedItem();
        if(traerservivo=="Bovinos"){
            jLabel2.setText("Fecha de Nacimiento");
            jLabel3.setText("Calorias por porcion");
        }else if(traerservivo=="Felinos"){
            jLabel2.setText("Fecha de Nacimiento");
            jLabel3.setText("Juguete Favorito");
        }else if(traerservivo=="Suculentas"){
            jLabel2.setText("Forma de hoja");
            jLabel3.setText("Tipo de Suculenta");
        }else if (traerservivo=="Verduras"){
            jLabel2.setText("Forma de hoja");
            jLabel3.setText("Calorias por porcion");
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCadaEjemplar2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDato1;
    private javax.swing.JTextField txtDato2;
    private javax.swing.JTextField txtDato3;
    // End of variables declaration//GEN-END:variables
}
