/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import clases.Conexion;
import clases.Servivo;
import java.sql.Connection;
import java.util.ArrayList;



/**
 *
 * @author Jose David
 */
public class InformacionCadaEjemplar extends javax.swing.JFrame {
    static Connection cn;
    int bloquear;
    /**
     * Creates new form InformacionCadaEjemplar
     */
    public InformacionCadaEjemplar() {
        initComponents();
        this.setLocationRelativeTo(null);
        Conexion cx = new Conexion();
        cn = cx.conectarMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlNumeroEjemplares = new javax.swing.JLabel();
        jcElegir = new javax.swing.JComboBox<>();
        jlPorIngresar = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Exposicion");

        jlNumeroEjemplares.setText("Ejemplares :");

        jcElegir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Bovinos", "Felinos", "Suculentas", "Verduras" }));
        jcElegir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcElegirItemStateChanged(evt);
            }
        });

        jlPorIngresar.setText("Ejemplares por ingresar :");

        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPorIngresar)
                            .addComponent(jlNumeroEjemplares)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jcElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jlNumeroEjemplares)
                .addGap(27, 27, 27)
                .addComponent(jlPorIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
       if (bloquear ==1){
           btnAceptar.setEnabled(true);
       InformacionCadaEjemplar2 a = new InformacionCadaEjemplar2();
       a.setVisible(true);
       this.dispose();

       }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void jcElegirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcElegirItemStateChanged
        int guardarcantidad = 0;
        int elegirServivo = jcElegir.getSelectedIndex();
        String cant = (String) jcElegir.getSelectedItem();
        ArrayList <String> most = new ArrayList<>();
        most = Servivo.Revisarnombre(cn);
        int r= most.size()-1;
        if (elegirServivo == 1) {
            for (int i = 0; i <= r; i++) {
                if (most.get(i).equals("Bovinos")) {
                    guardarcantidad=Integer.parseInt( most.get(i + 1));
                    bloquear = 1;
                    btnAceptar.setEnabled(true);
                }
            }
        }else if(elegirServivo == 2){
            for (int i = 0; i <= r; i++) {
                if (most.get(i).equals("Felinos")) {
                    guardarcantidad=Integer.parseInt( most.get(i + 1));
                    bloquear = 1;
                    btnAceptar.setEnabled(true);
                }
            }
        }else if(elegirServivo == 3){
            for (int i = 0; i <= r; i++) {
                if (most.get(i).equals("Suculentas")) {
                    guardarcantidad=Integer.parseInt( most.get(i + 1));
                    bloquear = 1;
                    btnAceptar.setEnabled(true);
                }
            }
        }else if (elegirServivo == 4){
           for (int i = 0; i <= r; i++) {
                if (most.get(i).equals("Verduras")) {
                    guardarcantidad=Integer.parseInt( most.get(i + 1));
                    bloquear = 1;
                    btnAceptar.setEnabled(true);
                }
            } 
        }else if (elegirServivo == 0){
            bloquear = 0;
            btnAceptar.setEnabled(false);
            jlNumeroEjemplares.setText("Ejemplares : "+0);
            jlPorIngresar.setText("Ejemplares por ingresar :"+0);
        }
        if (guardarcantidad == 0 ){
            bloquear = 0;
            btnAceptar.setEnabled(false);
            jlNumeroEjemplares.setText("Ejemplares : "+0);
            jlPorIngresar.setText("Ejemplares por ingresar :"+0);
        }
       if(elegirServivo != 0 && guardarcantidad != 0){
       jlNumeroEjemplares.setText("Ejemplares : "+guardarcantidad);
       int falta=Servivo.cantidadRegistro(cn, cant);
       int total = guardarcantidad-falta;
       jlPorIngresar.setText("Ejemplares por ingresar :"+total);
    }
    }//GEN-LAST:event_jcElegirItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCadaEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCadaEjemplar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JComboBox<String> jcElegir;
    private javax.swing.JLabel jlNumeroEjemplares;
    private javax.swing.JLabel jlPorIngresar;
    // End of variables declaration//GEN-END:variables
}
