/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgfinal;

import clases.Conexion;
import javax.swing.SpinnerNumberModel;
import clases.Servivo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Spinner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jose David
 */
public class IngresarSerVivo extends javax.swing.JFrame {
    Connection cn;
    /** Creates new form IngresarSerVivo */
    public IngresarSerVivo() {
        initComponents();
        this.setLocationRelativeTo(null);
        Conexion cx = new Conexion();
        cn = cx.conectarMySQL();
     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIngresarNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroEjemplares = new javax.swing.JTextField();
        jcZona = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre");

        jLabel2.setText("Numero de ejemplares");

        jcZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Zona Norte", "Zona Sur", "Zona Oriente", "Zona Occidente", "Zona Centro" }));
        jcZona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcZonaItemStateChanged(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        jLabel3.setText("Ubicacion");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcZona, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNumeroEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(84, 84, 84)
                                    .addComponent(txtIngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcZona, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jSpinner1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void jcZonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcZonaItemStateChanged
        SpinnerNumberModel nm = new SpinnerNumberModel();
        int elegirZona =jcZona.getSelectedIndex();
        jSpinner1.setEnabled(true);
        if (elegirZona == 1 || elegirZona == 2) {

            nm.setMaximum(4);
            nm.setMinimum(1);
            nm.setStepSize(1);
            nm.setValue(1);
        } else if (elegirZona == 5) {

            nm.setMaximum(8);
            nm.setMinimum(1);
            nm.setStepSize(1);
            nm.setValue(1);
        } else if (elegirZona == 3 || elegirZona == 4) {
            nm.setMaximum(3);
            nm.setMinimum(1);
            nm.setStepSize(1);
            nm.setValue(1);
        } else {
            jSpinner1.setEnabled(false);
        }

        jSpinner1.setModel(nm);
    }//GEN-LAST:event_jcZonaItemStateChanged

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        int bandera=0;
        int bandera2=1;
        String nombre = txtIngresarNombre.getText();
        int cantidad = Integer.parseInt(txtNumeroEjemplares.getText());
        int numerozona = (Integer) jSpinner1.getValue();
        String zona = numerozona+"-"+(String) jcZona.getSelectedItem();
        
        SpinnerNumberModel nm = new SpinnerNumberModel();
        int elegirZona =jcZona.getSelectedIndex();
        
            if (elegirZona == 1) {
                if (cantidad > 8 || cantidad < 4) {
                    JOptionPane.showMessageDialog(null, "En la Zona Norte MIN :4 y MAX: 8");
                    bandera = 0;
                } else {
                    bandera = 1;
                }
            }
            if (elegirZona == 2) {
                if (cantidad > 7 || cantidad < 3) {
                    JOptionPane.showMessageDialog(null, "En la Zona Sur MIN :3 y MAX: 7");
                    bandera = 0;
                } else {
                    bandera = 1;
                }
            }
            if (elegirZona == 3) {
                if (cantidad > 13 || cantidad < 7) {
                    JOptionPane.showMessageDialog(null, "En la Zona Oriente MIN :7 y MAX: 13");
                    bandera = 0;
                } else {
                    bandera = 1;
                }
            }
            if (elegirZona == 4) {
                if (cantidad > 14 || cantidad < 8) {
                    JOptionPane.showMessageDialog(null, "En la Zona Occidente MIN :8 y MAX: 14");
                    bandera = 0;
                } else {
                    bandera = 1;
                }
            }
            if (elegirZona == 5) {
                if (cantidad > 12 || cantidad < 6) {
                    JOptionPane.showMessageDialog(null, "En la Zona Centro MIN :6 y MAX: 12");
                    bandera = 0;
                } else {
                    bandera = 1;
                }
            }
         ArrayList<String> zon =new ArrayList<String>();
         zon = Servivo.RevisarZona(cn);
         for (int i = 0; i < zon.size(); i++) {
            if (zona .equals( zon.get(i))){
                JOptionPane.showMessageDialog(null, "este cubiculo " + zona +" esta ocupado");
                bandera2 = 0;
            }else{
            }
        }
        if (bandera == 1){
            if(bandera2 == 1){
                Servivo.IngresarSerVivo(cn, nombre, cantidad, zona);
                Interfaz1.Actualizar();
            }
        }
       
    }//GEN-LAST:event_btnAceptarMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarSerVivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarSerVivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarSerVivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarSerVivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarSerVivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> jcZona;
    private javax.swing.JTextField txtIngresarNombre;
    private javax.swing.JTextField txtNumeroEjemplares;
    // End of variables declaration//GEN-END:variables

}
