/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import clases.Bovino;
import clases.Conexion;
import java.awt.Color;
import javax.swing.JLabel;
import clases.Servivo;
import java.beans.XMLDecoder;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose David
 */
public class Interfaz1 extends javax.swing.JFrame {
    public static Connection cn;
    public static String m = null;
    
    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        Conexion cx = new Conexion();
        cn = cx.conectarMySQL();
        Actualizar();
        
        //
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlNorte2 = new javax.swing.JLabel();
        jlNorte1 = new javax.swing.JLabel();
        jlNorte3 = new javax.swing.JLabel();
        jlNorte4 = new javax.swing.JLabel();
        jlCenter1 = new javax.swing.JLabel();
        jlCenter2 = new javax.swing.JLabel();
        jlCenter3 = new javax.swing.JLabel();
        jlCenter4 = new javax.swing.JLabel();
        jlCenter5 = new javax.swing.JLabel();
        jlCenter6 = new javax.swing.JLabel();
        jlCenter7 = new javax.swing.JLabel();
        jlCenter8 = new javax.swing.JLabel();
        jlSur1 = new javax.swing.JLabel();
        jlSur2 = new javax.swing.JLabel();
        jlSur3 = new javax.swing.JLabel();
        jlSur4 = new javax.swing.JLabel();
        jlOeste1 = new javax.swing.JLabel();
        jlOeste2 = new javax.swing.JLabel();
        jlOeste3 = new javax.swing.JLabel();
        jlEste2 = new javax.swing.JLabel();
        jlEste1 = new javax.swing.JLabel();
        jlEste3 = new javax.swing.JLabel();
        btnSugerirPuesto = new javax.swing.JButton();
        btnPorcentajeOcupacion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIngresarExposicion = new javax.swing.JButton();
        btnDesocuparPuesto = new javax.swing.JButton();
        btnInformacionEjemplar = new javax.swing.JButton();
        btnEdadPromedio = new javax.swing.JButton();
        btnConsumoMinimo = new javax.swing.JButton();
        btnConsumoMaximo = new javax.swing.JButton();
        btnVerEjemplares = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlNorte2.setBackground(new java.awt.Color(102, 255, 51));
        jlNorte2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNorte2.setText("2");
        jlNorte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlNorte2.setOpaque(true);

        jlNorte1.setBackground(new java.awt.Color(102, 255, 51));
        jlNorte1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNorte1.setText("1");
        jlNorte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlNorte1.setOpaque(true);

        jlNorte3.setBackground(new java.awt.Color(102, 255, 51));
        jlNorte3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNorte3.setText("3");
        jlNorte3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlNorte3.setOpaque(true);

        jlNorte4.setBackground(new java.awt.Color(102, 255, 51));
        jlNorte4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNorte4.setText("4");
        jlNorte4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlNorte4.setOpaque(true);

        jlCenter1.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter1.setText("1");
        jlCenter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter1.setOpaque(true);

        jlCenter2.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter2.setText("2");
        jlCenter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter2.setOpaque(true);

        jlCenter3.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter3.setText("3");
        jlCenter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter3.setOpaque(true);

        jlCenter4.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter4.setText("4");
        jlCenter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter4.setOpaque(true);

        jlCenter5.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter5.setText("5");
        jlCenter5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter5.setOpaque(true);

        jlCenter6.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter6.setText("6");
        jlCenter6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter6.setOpaque(true);

        jlCenter7.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter7.setText("7");
        jlCenter7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter7.setOpaque(true);

        jlCenter8.setBackground(new java.awt.Color(102, 255, 51));
        jlCenter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCenter8.setText("8");
        jlCenter8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlCenter8.setOpaque(true);

        jlSur1.setBackground(new java.awt.Color(102, 255, 51));
        jlSur1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSur1.setText("1");
        jlSur1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlSur1.setOpaque(true);

        jlSur2.setBackground(new java.awt.Color(102, 255, 51));
        jlSur2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSur2.setText("2");
        jlSur2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlSur2.setOpaque(true);

        jlSur3.setBackground(new java.awt.Color(102, 255, 51));
        jlSur3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSur3.setText("3");
        jlSur3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlSur3.setOpaque(true);

        jlSur4.setBackground(new java.awt.Color(102, 255, 51));
        jlSur4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSur4.setText("4");
        jlSur4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlSur4.setOpaque(true);

        jlOeste1.setBackground(new java.awt.Color(102, 255, 51));
        jlOeste1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOeste1.setText("1");
        jlOeste1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlOeste1.setOpaque(true);

        jlOeste2.setBackground(new java.awt.Color(102, 255, 51));
        jlOeste2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOeste2.setText("2");
        jlOeste2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlOeste2.setOpaque(true);

        jlOeste3.setBackground(new java.awt.Color(102, 255, 51));
        jlOeste3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOeste3.setText("3");
        jlOeste3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlOeste3.setOpaque(true);

        jlEste2.setBackground(new java.awt.Color(102, 255, 51));
        jlEste2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEste2.setText("2");
        jlEste2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlEste2.setOpaque(true);

        jlEste1.setBackground(new java.awt.Color(102, 255, 51));
        jlEste1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEste1.setText("1");
        jlEste1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlEste1.setOpaque(true);

        jlEste3.setBackground(new java.awt.Color(102, 255, 51));
        jlEste3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEste3.setText("3");
        jlEste3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlEste3.setOpaque(true);

        btnSugerirPuesto.setText("Sugerir puesto");
        btnSugerirPuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSugerirPuestoMouseClicked(evt);
            }
        });

        btnPorcentajeOcupacion.setText("Porcentaje de Ocupacion");
        btnPorcentajeOcupacion.setPreferredSize(new java.awt.Dimension(103, 23));
        btnPorcentajeOcupacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPorcentajeOcupacionMouseClicked(evt);
            }
        });

        jLabel5.setText("Libre");

        jLabel6.setBackground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("               ");
        jLabel6.setOpaque(true);

        jLabel7.setText("Ocupado");

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("               ");
        jLabel8.setOpaque(true);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rosa-de-los-vientos.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Ejemplares", "Cubículos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnIngresarExposicion.setText("Ingresar Exposicion");
        btnIngresarExposicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarExposicionMouseClicked(evt);
            }
        });

        btnDesocuparPuesto.setText("Desocupar Puesto");
        btnDesocuparPuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesocuparPuestoMouseClicked(evt);
            }
        });

        btnInformacionEjemplar.setText("Ingresar informacion de cada ejemplar");
        btnInformacionEjemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformacionEjemplarMouseClicked(evt);
            }
        });

        btnEdadPromedio.setText("Edad Promedio");
        btnEdadPromedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdadPromedioMouseClicked(evt);
            }
        });

        btnConsumoMinimo.setText("Consumo Minimo");
        btnConsumoMinimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsumoMinimoMouseClicked(evt);
            }
        });

        btnConsumoMaximo.setText("Consumo Maximo");
        btnConsumoMaximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsumoMaximoMouseClicked(evt);
            }
        });

        btnVerEjemplares.setText("Ver informacion los ejemplares");
        btnVerEjemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerEjemplaresMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Exposición de Seres vivos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSugerirPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPorcentajeOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jlSur1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlCenter5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlOeste1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jlOeste2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jlOeste3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlCenter1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jlNorte1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlNorte2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlNorte3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlNorte4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlCenter2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlCenter3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlCenter4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlCenter6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlCenter7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlCenter8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlSur2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlSur3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlSur4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEste1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEste2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEste3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnIngresarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDesocuparPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEdadPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInformacionEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsumoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsumoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNorte1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNorte2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNorte3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNorte4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCenter1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCenter2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCenter3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCenter4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCenter6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCenter5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCenter7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCenter8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSur1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSur2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSur3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSur4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jlOeste1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlOeste2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlOeste3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSugerirPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPorcentajeOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jlEste2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jlEste3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnIngresarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDesocuparPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(9, 9, 9)
                                .addComponent(btnInformacionEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdadPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsumoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsumoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlEste1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnVerEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSugerirPuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSugerirPuestoMouseClicked
        SugerirPuesto a = new SugerirPuesto();
        a.setVisible(true);
        
       
    }//GEN-LAST:event_btnSugerirPuestoMouseClicked

    private void btnIngresarExposicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarExposicionMouseClicked
        IngresarSerVivo b = new IngresarSerVivo();
        b.setVisible(true);
        ArrayList<String> cantidad = new ArrayList<>();
        cantidad = Servivo.Revisarnombre(cn);
    }//GEN-LAST:event_btnIngresarExposicionMouseClicked

    private void btnInformacionEjemplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacionEjemplarMouseClicked
        InformacionCadaEjemplar c = new InformacionCadaEjemplar();
        c.setVisible(true);
    }//GEN-LAST:event_btnInformacionEjemplarMouseClicked

    private void btnEdadPromedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdadPromedioMouseClicked
        EdadPromedio d = new EdadPromedio();
        d.setVisible(true);
    }//GEN-LAST:event_btnEdadPromedioMouseClicked

    private void btnConsumoMinimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumoMinimoMouseClicked
        ConsumoMinimo e = new ConsumoMinimo();
        e.setVisible(true);

    }//GEN-LAST:event_btnConsumoMinimoMouseClicked

    private void btnConsumoMaximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumoMaximoMouseClicked
        ConsumoMaximo f = new ConsumoMaximo();
        f.setVisible(true);
    }//GEN-LAST:event_btnConsumoMaximoMouseClicked

    private void btnDesocuparPuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesocuparPuestoMouseClicked
        int filaseleccionada = jTable1.getSelectedRow();
        
        if (filaseleccionada==-1){
         
             JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");

         }else{

            DefaultTableModel modelotabla=(DefaultTableModel) jTable1.getModel();
            String zona=(String)modelotabla.getValueAt(filaseleccionada, 2);
            m = zona;
            Servivo.Borrar(cn, zona);
            Actualizar();
             
        }
    }//GEN-LAST:event_btnDesocuparPuestoMouseClicked

    private void btnPorcentajeOcupacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPorcentajeOcupacionMouseClicked

        ArrayList<String> zon =new ArrayList<String>();
        zon = Servivo.RevisarZona(cn);
        int llenos = zon.size();
        float resultado = (float)(100*llenos)/21;
        JOptionPane.showMessageDialog(null, "OCUPADO: "+String.format("%.2f", resultado)+"%");
    }//GEN-LAST:event_btnPorcentajeOcupacionMouseClicked

    private void btnVerEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEjemplaresMouseClicked
        ImprimirInformacion e = new ImprimirInformacion();
        e.setVisible(true);
    }//GEN-LAST:event_btnVerEjemplaresMouseClicked
    public static void Actualizar(){

        int a ;int b;int c;
       String ver;
       String ver2;
       int f;
       jTable1.setModel(Servivo.buscarTabla(cn));
       ArrayList<String> zon =new ArrayList<String>();
       zon = Servivo.RevisarZona(cn);
       if (m!=null){
           f=1;
       }else{
           f=zon.size();
       }
           
        for (int i = 0; i < f; i++) {
            if (m != null) {
                String[] numeros = m.split("-");
                ver=numeros[0];
                ver2=numeros[1];
                a=102;
                b=255;
                c=51;
            } else {
                String[] numeros = zon.get(i).split("-");
                ver=numeros[0];
                ver2=numeros[1];
                a=204;
                b=0;
                c=0;
                
            }
            int numerocolor = Integer.parseInt(ver);
            if (ver2.equals("Zona Norte")) {

                switch (numerocolor) {
                    case 1:
                        jlNorte1.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 2:
                        jlNorte2.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 3:
                        jlNorte3.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 4:
                        jlNorte4.setBackground(new java.awt.Color(a, b, c));
                        break;
                }
            }
            if (ver2.equals("Zona Sur")) {

                switch (numerocolor) {
                    case 1:
                        jlSur1.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 2:
                        jlSur2.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 3:
                        jlSur3.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 4:
                        jlSur4.setBackground(new java.awt.Color(a, b, c));
                        break;
                }
            }
            if (ver2.equals("Zona Occidente")) {

                switch (numerocolor) {
                    case 1:
                        jlOeste1.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 2:
                        jlOeste2.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 3:
                        jlOeste3.setBackground(new java.awt.Color(a, b, c));
                        break;
                }
            }
            if (ver2.equals("Zona Oriente")) {

                switch (numerocolor) {
                    case 1:
                        jlEste1.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 2:
                        jlEste2.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 3:
                        jlEste3.setBackground(new java.awt.Color(a, b, c));
                        break;
                }
            }
            if (ver2.equals("Zona Centro")) {

                switch (numerocolor) {
                    case 1:
                        jlCenter1.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 2:
                        jlCenter2.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 3:
                        jlCenter3.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 4:
                        jlCenter4.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 5:
                        jlCenter5.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 6:
                        jlCenter6.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 7:
                        jlCenter7.setBackground(new java.awt.Color(a, b, c));
                        break;
                    case 8:
                        jlCenter8.setBackground(new java.awt.Color(a, b, c));
                        break;

                }

          
             
            }

        }
        m=null;
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsumoMaximo;
    private javax.swing.JButton btnConsumoMinimo;
    private javax.swing.JButton btnDesocuparPuesto;
    private javax.swing.JButton btnEdadPromedio;
    private javax.swing.JButton btnInformacionEjemplar;
    private javax.swing.JButton btnIngresarExposicion;
    private javax.swing.JButton btnPorcentajeOcupacion;
    private javax.swing.JButton btnSugerirPuesto;
    private javax.swing.JButton btnVerEjemplares;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JLabel jlCenter1;
    public static javax.swing.JLabel jlCenter2;
    public static javax.swing.JLabel jlCenter3;
    public static javax.swing.JLabel jlCenter4;
    public static javax.swing.JLabel jlCenter5;
    public static javax.swing.JLabel jlCenter6;
    public static javax.swing.JLabel jlCenter7;
    public static javax.swing.JLabel jlCenter8;
    public static javax.swing.JLabel jlEste1;
    public static javax.swing.JLabel jlEste2;
    public static javax.swing.JLabel jlEste3;
    public static javax.swing.JLabel jlNorte1;
    public static javax.swing.JLabel jlNorte2;
    public static javax.swing.JLabel jlNorte3;
    public static javax.swing.JLabel jlNorte4;
    public static javax.swing.JLabel jlOeste1;
    public static javax.swing.JLabel jlOeste2;
    public static javax.swing.JLabel jlOeste3;
    public static javax.swing.JLabel jlSur1;
    public static javax.swing.JLabel jlSur2;
    public static javax.swing.JLabel jlSur3;
    public static javax.swing.JLabel jlSur4;
    // End of variables declaration//GEN-END:variables
}
