/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import clases.Conexion;
import java.util.ArrayList;
import clases.Servivo;
import static java.lang.System.console;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose David
 */
public class SugerirPuesto extends javax.swing.JFrame {
    static Connection cn;
    /**
     * Creates new form Desocupar
     */
    public SugerirPuesto() {
        initComponents();
        this.setLocationRelativeTo(null);
        Conexion cx = new Conexion();
        cn = cx.conectarMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumeroEjemplares = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Numero de Ejemplares:  ");

        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        ArrayList <String> puesto = new ArrayList<>();
        String mostrar="";
        int conv = Integer.parseInt(txtNumeroEjemplares.getText());
        puesto = Servivo.RevisarZona(cn); 
        if (conv>=4 && conv<=8){
            for (int i = 1; i <= 4; i++) {
                String b =i+"-"+"Zona Norte";
                boolean g = puesto.contains(b);
                if (g==false) {
                    mostrar = mostrar +"En la cubiculo  "+b+"  el MIN:4 y MAX:8    \n";
                }
            }
        }
        if (conv>=3 && conv<=7){
            for (int i = 1; i <= 4; i++) {
                String b =i+"-"+"Zona Sur";
                boolean g = puesto.contains(b);
                if (g==false) {
                    mostrar = mostrar +"En la cubiculo  "+b+"  el MIN:3 y MAX:7    \n";
                }
            }
        }
        if (conv >= 7 && conv <= 13) {
            for (int i = 1; i <= 3; i++) {
                String b = i + "-" + "Zona Oriente";
                boolean g = puesto.contains(b);
                if (g == false) {
                    mostrar = mostrar + "En la cubiculo  " + b + "  el MIN:7 y MAX:13    \n";
                }
            }
        }
        if (conv >= 8 && conv <= 14) {
            for (int i = 1; i <= 3; i++) {
                String b = i + "-" + "Zona Occidente";
                boolean g = puesto.contains(b);
                if (g == false) {
                    mostrar = mostrar + "En la cubiculo  " + b + "  el MIN:8 y MAX:14    \n";
                }
            }
        }
        if (conv >= 6 && conv <= 12) {
            for (int i = 1; i <= 8; i++) {
                String b = i + "-" + "Zona Centro";
                boolean g = puesto.contains(b);
                if (g == false) {
                    mostrar = mostrar + "En la cubiculo  " + b + "  el MIN:6 y MAX:12    \n";
                }
            }
        }
        if (conv > 14 || conv < 3) {
            mostrar="No hay cubiculos con esa cantidad";
        }

                 
        JOptionPane.showMessageDialog(null, mostrar);
        
    }//GEN-LAST:event_btnAceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SugerirPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SugerirPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SugerirPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SugerirPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SugerirPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumeroEjemplares;
    // End of variables declaration//GEN-END:variables
}
